### ISSUE TITLE
Stability issues, sometimes nue renders an extension as raw markdown for no apparent reason

### ISSUE THREAD

**Issue by goblinfactory** [nuejs/nue#361] opened 2024-09-12 19:23 UTC
### sometimes nue renders an extension as raw markdown for no apparent reason

This is hard to describe; I was actually right in the middle of writing a blog post about it, in my review when I decided it's probably something small and will just go away and if it comes back, I should publish the page to build server to see if it's local to my machine or actually a nue issue. 

The screenshot below on the right is screenshot from my blog (review) which is LIVE, and on the left is the code I had just committed; you can see nue rendered the first image tag as RAW markdown and the second tag as an image.

[You can see the bug in LIVE here;](https://nue-beta-review.bignamehunter.com/blog/bugs-and-issues#:~:text=Libraries%2C%20Include%2C%20Exclude) 

<img width="1074" alt="Screenshot 2024-09-12 at 20 15 55" src="https://github.com/user-attachments/assets/31d0829f-56a9-488f-9e14-268cfb7a0056">

Depending on the root cause of the issue; it would make sense that the issue is very likely not limited to  just the [img] tag. 

### Environment

- OS: OSX
- Nuekit Version: Nue 1.0.0-beta.2 • Bun 1.1.27 

### Minimal steps to reproduce

1. Download this starter project based on `nue create` from : https://github.com/goblinfactory/2024-nue-beta-review/releases/tag/issue-361
2. run `nue` from root
3. open browser, navigate to `/blog/bugs-and-issues` observe error.

**Comment by nobkd** [comment] 2024-09-12 19:54
Can you check, if the line endings in the file are consistent, please? We had an issue #307, where the rendering failed because of that, and I made a PR to fix this behavior, but maybe I overlooked some instance of that...

`cat -e <file>` shows crlf as `^M$` and lf as `$`

But this is probably only the reason, when this happens repeatably, e.g. removing dist and re-rendering without md changes.

(I suspected this, because you mentioned in the post, that this sometimes only ges fixed, when pasting from another file)


I saved my file with crlf and it didn't change anything :shrug:

---

I will try to reproduce this issue, but it currently doesn't seem to happen for me. Sry

**Comment by goblinfactory** [comment] 2024-09-12 21:16
@nobkd  I ran this on my machine
```bash
find . -type f -not -path "./node_modules/*" -exec file {} \; | grep CRLF
```
in the root and got no results.

wrt to reproducing; It's 100% reproducible because the build agent on Cloudflare, which is a totally unbiast and stable build agent gives the exact same result. 

I can give you read access to the review website repo if you want to pull that and test it, since the build agent was able to repro the behaviour from that code.

**Comment by nobkd** [comment] 2024-09-12 21:41
Thank you, @goblinfactory. I can't promise anything, but maybe we can find at least *some* reason. :)

**Comment by goblinfactory** [comment] 2024-09-12 21:45
@nobkd  I moved the repo and made it public; 
https://github.com/goblinfactory/2024-nue-beta-review
I've setup a new git integration and take down the build agent and create a new pages project to use the new repo;
new live site is on a new server and still gives the same error.
gimme a minute and I'll create a release so you can download a rar/zip, which will be much easier to test.

**Comment by goblinfactory** [comment] 2024-09-12 21:50
ok, done, so ...steps to reliably reproduce (every time)

## steps to reproduce

1. Download this starter project based on `nue create` from : https://github.com/goblinfactory/2024-nue-beta-review/releases/tag/issue-361
2. run `nue` from root
3. open browser, navigate to `/blog/bugs-and-issues` observe error.

**Comment by nobkd** [comment] 2024-09-12 21:54
There's a space after the first `[! ...]` image... That seems to break the transformation...

This is really unreasonable, and should be fixed in nue...

**Comment by goblinfactory** [comment] 2024-09-12 21:57
Aaaaah, you're a superstar! 
does that same issue impact any other tags?

**Comment by nobkd** [comment] 2024-09-12 21:59
I tested with the button at the end of the same page, and yes, it does..

**Comment by goblinfactory** [comment] 2024-09-12 22:00
@nobkd 
I concur with your findings. Just tested it myself.
Do you want to do the honors and create a new separate un-messy issue for that?
;D

**Comment by goblinfactory** [comment] 2024-09-12 22:00
@nobkd  also, I guess, support inline markdown would also fix it? Or, would have most likely have required fixing this along the way. Random thought.

**Comment by nobkd** [comment] 2024-09-12 22:04
> create a new separate un-messy issue

Sure, I'll do. Please correct my issue, if I forgot something.

(Yes, inline support should also fix this.)

**Comment by nobkd** [comment] 2024-09-12 22:13
Closing, as moved to #362

**Closed as completed by nobkd** 2024-09-12 22:13 UTC
Labels: nuemark
