### ISSUE TITLE
The system memory is exhausted.

### ISSUE THREAD

**Issue by jbguo424** [nuejs/nue#386] opened 2024-10-21 06:09 UTC
### Describe the Bug
The system memory is exhausted within 30 minutes.
75.7g   4.3g  40096 R 133.3  14.9   6:14.20 bun
91.5g  20.6g  40096 R 137.5  70.9  30:25.59 bun

### Environment
uname -a
Linux dlp 6.8.0-47-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct  2 16:16:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

Dmesg info
[24412.412574] Purging GPU memory, 0 pages freed, 0 pages still pinned, 215 pages left available.
[24412.412623] wpa_supplicant invoked oom-killer: gfp_mask=0x140cca(GFP_HIGHUSER_MOVABLE|__GFP_COMP), order=0, oom_score_adj=0
[24412.412626] CPU: 12 PID: 846 Comm: wpa_supplicant Not tainted 6.8.0-47-generic #47~22.04.1-Ubuntu
[24412.412627] Hardware name: Dell Inc. XPS 8960/09M47G, BIOS 2.9.1 08/09/2024

### Minimal Reproduction
I downloaded the source code from GitHub and then used the command nue to launch the site under nue/package/nuejs.org.
~/nue/packages/nuejs.org$ nue

**Comment by nobkd** [comment] 2024-10-21 07:00
So. You installed `nuekit` globally, and run it with `bun` (shebang not changed) in the docs (nuejs.org directory) on the `master` branch. Then you used some utility to check the memory usage. Correct?

Did you check, if it really was nue's bun process? Did you do anything else after starting nue? Did you edit files in the docs?

Please provide steps, on what exactly you did, because I tried to reproduce this issue, and could not. Thank you

**Comment by jbguo424** [comment] 2024-10-21 14:49
Hello nobkd,

Thank you very much for your reply.

I followed the steps in the official tutorial.
1. curl -fsSL https://bun.sh/install | bash
2. bun install nuekit --global
3. run command nue under the directory nue/package/nuejs.org/

I modified some .md files after starting Nue.

Thanks,

**Comment by nobkd** [comment] 2024-10-30 21:20
I tried your steps, even using the same operating system (22.04.1-Ubuntu) in a vm but couldn't reproduce this. Can you reproduce it reliably?

- What version of bun were you using?
- Did you show the web page in the browser while editing the md files?
- Do you remember, this issue appeared after you put in a special character sequence or so?
- Did you use the `dev` branch or were you on the `master` branch when you ran `nue` in `packages/nuejs.org`?

Im sorry to bother you like this, but as I cannot reproduce it, I want to gather all possible clues to find out, if there is a pattern which I can use to also reproduce this locally.
If you also can't reproduce it now, we can't do anything but guess what might have happened there...

If you still remember anything that might seem important, please let me know :)

Thank you for your time

**Comment by tipiirai** [comment] 2024-11-14 11:27
Probably a long shot, but the latest Bun release uses less memory in long-running processes. 

https://bun.sh/blog/bun-v1.1.34

As for now, I'm out of ideas why this happens since I have a Mac where this doesn't happen

**Comment by nobkd** [comment] 2024-11-14 18:33
Closing. If it occurs again to you, please reopen / leave a comment.
If you find a way to make it reproducible, even better!

**Closed as not planned** 2024-11-14 18:33 UTC
