### ISSUE TITLE
Support inline <span> components in markdown

### ISSUE THREAD

**Issue by goblinfactory** [nuejs/nue#348] opened 2024-09-10 19:13 UTC
### Is your feature request or improvement related to a problem?

I wanted to create a `pill` component as follows; somewhat psuedo
```html
<div @name="pill" class="pill">
    <slot/>
</div>
```
I also tried
```html
<div @name="pill" class="pill">
    {text}
</div>
```

and was unable to use it in markdown;
```markdown
[pill]
    text: my pill
```
Both options gives me runtime error in chrome console

```bash
mount.js:18 Uncaught (in promise) TypeError: Failed to resolve module specifier ''
    at importAll (mount.js:18:21)
    at mountAll (mount.js:26:30)
    at patch (hotreload.js:53:9)
    at async sse.onmessage (hotreload.js:84:7)
```
The documentation does not explain how to create a component. There are some vague notes on constructors. But no worked examples.

### Solution you'd like

1. I'd like the vagueness in the documentation around building components to be removed by providing a full worked example of some small simple component. Both how to create the component, and how to use it. 

_update: it's possible there is a different bug causing the "failed to resolve module specifier" which might mean the current docs are sufficient. (I can't tell while I'm getting this error since I dont know what I dont know.)_

2. I'd like to be able to able to create "inline" `<span>` components for items like "pills".  (css styled rounded end tags)
3. I'd want to be able to invoke the components inline in markdown for easier testing and more flexibility using both html syntax as well as markdown sytnax as follows

```markdown
This is my inline [pill hello!] and also <pill text="hello"/>!
```

**Comment by nobkd** [comment] 2024-09-10 19:47
1. Agreed
2. and 3.: Partial duplicate of #187

I will check, if I can get at least the non-inline variant to work.

**Comment by goblinfactory** [comment] 2024-09-10 21:41
@nobkd I'm still checking but I think the `Failed to resolve module specifier` is happening on a brand new `nue create` codebase without modifications; which may have led me totally down this rabbit hole. If I was able to get components working I'm fairly certain I would have been able to provide a much more coherant suggestion of improvement to documentation, with some simple getting started `exercises` that can be done with `nue` from scratch.

**Comment by goblinfactory** [comment] 2024-09-10 22:24
I've created a new bug report for the `failed to resolve` error;
https://github.com/nuejs/nue/issues/349
When that's resolved, this may or may not still be an issue.

**Comment by tipiirai** [comment] 2024-09-12 05:45
I started working on this, but then remembered how complex and unfriendly Marked API is. Doing this later. I have a custom Markdown parser implementation forming in my mind

**Comment by tipiirai** [comment] 2024-09-13 07:21
Ended up doing a custom Markdown parser/renderer that is easier to work with than Marked. Likely faster too. It's a bit of a work, but there are so many benefits to do this in-house (beyond the NIH syndrome) that will benefit Nue in the long run.

**Comment by nobkd** [comment] 2024-09-13 10:40
New side quest started ;)

Edit: On a side note: it would be nice to be able to extend the new md parser e. g. replacing something in MD before Parsing (or modify text leafs afterward).
(my use case is simple smartypants: replacing `--`, `---` with  `&ndash;` (`–`), `&mdash;` (`—`) or `...` with `&hellip;` (`…`) or `""`, `''` with `&bdquo;&rdquo;` (`„”`) (bottom double quote; right double quote) and `&sbquo;&rsquo;` (`‚’`) (single bottom quote; right single quote) (this would be for German. I think those were right, but I might have switched something up when copying / checking out)

**Comment by nobkd** [comment] 2024-11-03 12:08
Should work with `dev` branch.

Though I'm not sure, if `inline [.class]` would result in `<p>inline <span class="class"></span></p>` or in `<div class="class"></div></p>`
Probably it would be best to have it `span` for inline- and `div` for block-syntsx

**Closed as completed by nobkd** 2024-11-03 12:08 UTC
Labels: new feature, improvement, docs, nuemark
